import type { Metadata } from "next";
import { Oswald, Raleway } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NoiseBg from "@/components/NoiseBg/NoiseBg";
import Nav from "@/components/Nav/Nav";
import FinalCta from "@/components/FinalCTA/FinalCTA";

const oswald = Oswald({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "500", "600", "700"],
  variable: "--oswald",
});
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  variable: "--raleway",
});

const adedisplay = localFont({
  src: "../../public/fonts/adedisplay.otf",
  variable: "--adedisplay",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${oswald.variable} ${raleway.variable} ${adedisplay.variable}`}
      >
        <NoiseBg>
          <Nav />
          {children}
          <FinalCta />
        </NoiseBg>
      </body>
    </html>
  );
}
