import type { Metadata } from "next";
import { Inter, Oswald, Raleway } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NoiseBg from "@/components/NoiseBg/NoiseBg";
import Nav from "@/components/Nav/Nav";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const oswald = Oswald({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "500", "600", "700"],
  variable: "--oswald",
});
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  variable: "--raleway",
});

// const nyghtSerif = localFont({
//   src: "../../public/fonts/NyghtSerif.otf",
//   variable: "--nyghtSerif",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${oswald.variable} ${raleway.variable}`}>
        <NoiseBg>
          <Nav />
          {children}
          <Footer />
        </NoiseBg>
      </body>
    </html>
  );
}
